In [3]:
import numpy as np
import scipy

In [4]:
a = np.arange(25).reshape(5,5) + 1
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [10]:
def lu(a):
    n = len(a)
    L = [[0] * n for i in range(n)]
    U = [[0] * n for i in range(n)]
    for i in range(n):
        L[i][i] = 1
    for i in range(n):
        for j in range(n):
            U[i][j] = a[i,j]
    for i in range(n):
            for j in range(i, n):
                L[j][i] = (U[j][i])/(U[i][i])
    for k in range(1, n):
        for i in range(k-1, n):
            for j in range(i, n):
                L[j][i] = (U[j][i])/(U[i][i])
        for i in range(k, n):
            for j in range(k-1, n):
                U[i][j] = U[i][j] - L[i][k-1]*U[k-1][j]
    return L, U

In [6]:
def group_lu(L, U):
    LU = scipy.array(L) + scipy.array(U) - np.eye(len(L))
    return LU

In [68]:
def get_L(m):
    L = m.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i+1 :] = 0
    return np.array(L)

    
def get_U(m):
    U = m.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return np.array(U)

In [75]:
def solve_LU(lu_matrix, b):
    
    #Ax = b
    
    L = get_L(lu_matrix)
    U = get_U(lu_matrix)
    
    n = len(L)

    # (5) Perform substitutioan Ly=b
    y = [0 for i in range(n)]
    
    for i in range(n):
        y[i] = b[i]/float(L[i][i])
        for k in range(i):
            y[i] -= y[k]*L[i][k]

    n = len(U)

    # (6) Perform substitution Ux=y
    x = [0 for i in range(n)]
    for i in range(n-1,-1,-1):
        x[i] = y[i]/float(U[i][i])
        for k in range (i-1,-1,-1):
            U[i] -= x[i]*U[i][k]

    return x


In [77]:
A = [ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ]
A = scipy.array(A)
print("A", type(A))
L, U = lu(A)

LU = group_lu(L, U)


print(LU)
print(get_L(LU))
print(get_U(LU))

B =  [7, 3, -1, 2]

X = solve_LU(LU, B)

print(X)


# # print(A)
# print(scipy.array(L))
# print(scipy.array(U))

# print(scipy.array(L) + scipy.array(U) - np.eye(len(A)))
# print(np.dot(scipy.array(L), scipy.array(U)))


A <class 'numpy.ndarray'>
[[ 7.          3.         -1.          2.        ]
 [ 0.42857143  6.71428571  1.42857143 -4.85714286]
 [-0.14285714  0.21276596  3.55319149  0.31914894]
 [ 0.28571429 -0.72340426  0.08982036  1.88622754]]
[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]
[0, 0, 0, 0]
[1.0, 0.0, 0.0, 0.0]
