In [17]:
import numpy as np
import scipy

In [13]:
a = np.arange(25).reshape(5,5) + 1
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [35]:
def lu(a):
	n = len(a)
	L = [[0] * n for i in range(n)]
	U = [[0] * n for i in range(n)]
	for i in range(n):
		L[i][i] = 1
	for i in range(n):
		for j in range(n):
			U[i][j] = a[i,j]
	for i in range(n):
			for j in range(i, n):
				L[j][i] = (U[j][i])/(U[i][i])
	for k in range(1, n):
		for i in range(k-1, n):
			for j in range(i, n):
				L[j][i] = (U[j][i])/(U[i][i])
		for i in range(k, n):
			for j in range(k-1, n):
				U[i][j] = U[i][j] - L[i][k-1]*U[k-1][j]
	return L, U

In [53]:
def group_lu(L, U):
    LU = scipy.array(L) + scipy.array(U) - np.eye(len(L))
    return LU

In [57]:
A = ([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
A = scipy.array(A)
L, U = lu(A)


LU = group_lu(L, U)

B = np.dot(L, U) - A

print(B)

# # print(A)
# print(scipy.array(L))
# print(scipy.array(U))

# print(scipy.array(L) + scipy.array(U) - np.eye(len(A)))
# print(np.dot(scipy.array(L), scipy.array(U)))


[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.4408921e-16]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 4.4408921e-16 0.0000000e+00 0.0000000e+00]]


In [48]:
print(a[2, :2])
print(a[:, 2])

[20 21]
[12]
